server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/sale?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: 3141593
